UI Part for Filter & Search Utility
HaikuArchives/Calendar pull request #120
Opened 2022-07-06 11:22 UTC by harshit-sharma-gits

I have made the UI Part of the Filter & Search Issue #119, and it is looking like [this](https://gm1.ggpht.com/AMWwBltqesWgY_SY-4IoRUpWO897QTAfke5nBJbdrPAtL-4obBo0-_zQsOpshiwl0tneW_REG88w5uvNbQczCINxp8mslnEhqexh31Q54ATxu_rFHTWyFQuD58J2bemDXSNLz6Q68jsQ2YbFp75E9Ju7lVX2_uSnwW9Lo1D7bh9jlwR35pQRlY8zzshKxY3Fb5TpvPzBm1NPl5pdCaV9GVfbhR015QMFXAQR2I1WA86UzJXMk10JHb4MRvP1RxSCEojHDTuabDrUwNMtkPN_am3YM4m7HBb4MERNcihXXNKWWFINzbPbZnYUjKO6zpSvwuqpXFyYRgYpEfipjwkDQjkFua9o2XPsAKdSASQi7Q_T8YFX3GHRe8uvgSwiT7kXLu9CKst9wYoib943nSaM5vbHxX1C3lY42tIRLoFuGxua7YlHyCqqqdCN4MBm1nOhYjw3Z_ce-9dIwxpfkTe4ptsq2YCh_DxfgMQl5qBFHM44rSEAbpl_Iw0PFd6CMMAsv7U12ImjFloMDl_GG_DvxhrT-9BMMtNM43FF-ROEzRu_-3FmX30Y_AnaPKgisMeIgCuVv9q8XUt7U3RTU4QeRJKltywXOEUhjfq9Aa7rHfgX-7rpJopSwX1rC3yIi6A9ZgcusFpgIVwKEBbRWuOHjc0Q537c6xZkrcI7e11SdVMnuzCepCxfKxYYmsberSFIlHHysNLFyOa1oy0oaULG1nJ99x14852vEZHIjaXVi1Uak3xFJi15qhii6grIf5YGBgNvRzq_ryf0p-lPhY8mc8ORViCck51wzoes7Fg_lfTMWi89lwMHCMHv57w5oQLfecYN_ati_bQikkEQakkHk10Qj1DjnpI7DrxSVKEr4FPUXfe-vY80zQg-LmJ_jhLssA45bFB5-sGaN8n8XomCTQTAUg=s0-l75-ft-l75-ft)

Changes Summary:
* Added Profile MenuField and Category MenuField
(Currently, I have initialized them with random values)

* Added Search TextControl

Also, all the clickables present in the UI, currently sends a tempMessage that I created, and it is not functional yet

2022-07-06 13:05 UTC, humdingerb requested changes
I'm still not prepared to accept all that clutter in the main window.

I commented on it in #119, I wrote it in my last email where I offered how to start to tackle the feature, which was also ignored.
If after using the app a bit, it turns out more fine-grained filtering needs a category pop-up menu, there's no problem adding it. But to start out needlessly complicated...

Let's stick to one feature at a time, the filtering, and leave "profiles" until this one is working.

2022-07-06 16:45 UTC, harshit-sharma-gits commented
> If after using the app a bit, it turns out more fine-grained filtering needs a category pop-up menu, there's no problem adding it. But to start out needlessly complicated...
>
> Let's stick to one feature at a time, the filtering, and leave "profiles" until this one is working.

Okay, so should I remove the unnecessary things, that is, Profile and Categories MenuFiled.
And leave "Search" Text Control and the clear button there?

Well I don't think having the Clear button would be a nice thing, as only a Search Box is present, and if we implement a category popup menu in future, then we may have the Clear button as well.

2022-07-06 17:17 UTC, humdingerb commented
Yes, as I wrote in #119, just the BTextControl labelled "Filter:". No "Clear" button. It'd be nice to capture ESC to clear the filter. But that can come later.

2022-07-07 05:52 UTC, nielx commented on src/SidePanelView.cpp
> +
Extra whitespace

2022-07-07 06:06 UTC, nielx commented
I added some comments throughout the code.

Two general remarks about PR hygiene: 

1. Your changes are spread over three commits. While I can imagine you make these commits internally while working on it and wanting to keep the changes, when you are going to upstream these changes you generally want to clean them up, i.e. squash them into one commit. You also want to give them clear, concise commit messages about the change. 'Get Started' is not one of those.
2. You are adding the Calendar.pld file. It is fine to use this locally, but it should not be added remotely. The official build method is to use the Makefile, so we do not need additional IDE files for this. Please remove this from the commit.

Furthermore, I agree with @humdingerb about keeping it simple. As we discussed on our call on Sunday, let's start with text filtering. We can add the other things later.

2022-07-07 06:06 UTC, nielx requested changes
See individual comments and general comment.

2022-07-07 06:20 UTC, humdingerb reviewed
I suppose some comments a FYI only, since you'll remove some of the code when updating the PR anyway.

2022-07-07 06:20 UTC, humdingerb commented on src/SidePanelView.cpp
> +#include <MenuField.h>
Alphasort includes.

2022-07-07 06:20 UTC, humdingerb commented on src/SidePanelView.cpp
> +	fFilterSearchHeading = new BStringView(BRect(10,10,11,11), "filterSearchHeading", "Filter & Search");
You'd want to use the layout aware constructor without the first BRect parameter.
But: We don't need this heading anyway, the label "Filter:" of the BTextView is clue enough.

2022-07-07 06:29 UTC, humdingerb commented
> Two general remarks about PR hygiene:

WRT working on PRs in general, I recommend using "feature branches". There's a nice intro to it at https://github.com/haikuports/haikuports/wiki/DevelopmentModel
That way, you can easily leave your work in one branch for a bit and do some experimenting in another.

It's also a good idea to separate your work into distinct commits, e.g. do style fixes in one commit, GUI work in another and backend work in yet another. Before creating your PR, do a "git -i rebase" to move those commits around and squash the commits of a similar area.

2022-07-12 05:14 UTC, humdingerb commented
Anything new, @harshit-sharma-gits ?
It's been very quiet for too long...

2022-07-12 07:09 UTC, harshit-sharma-gits commented
Hello!
As mentioned, I have created a new branch, namely, filterFeature, for implementing the Filter Utility
And cleared the excess clutter from the main window, now the updated UI looks like this -

![UI Part Refined](https://user-images.githubusercontent.com/75475819/178426795-2347e929-0984-49d2-8520-cec0f3d34f3b.png)

Now, the current goal for the filter is to capture the keywords, and search them in the events list for the particular tab (Day, Week, or Month) and display them accordingly.

2022-07-12 14:34 UTC, humdingerb commented
You haven't pushed that branch to your repo, it appears. If you update this PR, we can keep track of your progress. Just adding a BTextControl to the window seems a bit scant for a week of full time work...
Do speak up when you're stuck somewhere and need some pointers.

2022-08-01 06:14 UTC, nielx commented
Superseded by PR #121

2022-08-01 06:14 UTC, closed without merging