Added a TextControl with Apply and Clear buttons
HaikuArchives/Calendar pull request #121
Opened 2022-07-16 18:48 UTC by harshit-sharma-gits

Apart from adding the above mentioned. Also, using message, I tried to clear out the `TextControl` with `SetText(NULL)` whenever the user presses the `Clear` Button, but it didn't seem to be working.

2022-07-17 04:10 UTC, humdingerb requested changes

2022-07-17 04:10 UTC, humdingerb commented on src/SidePanelView.cpp
> +	fTextFilter = new BTextControl("FilterString", NULL, NULL, NULL);;
Please check the class descriptions in the [BeBook](file:///boot/system/documentation/BeBook/BTextControl.html) and [Haiku Book](https://www.haiku-os.org/docs/api/classBTextControl.html).

You can pass the ctor a label and a BMessage that's send when the user sends their changes.

2022-07-17 04:10 UTC, humdingerb commented on src/SidePanelView.cpp
> +	fFilterApplyButton =
When using BTextControls messaging, no "Apply" button is needed.

2022-07-17 04:10 UTC, humdingerb commented on src/SidePanelView.cpp
> +		.AddStrut(80)
To align the widgets to the bottom of the window, use an .AddGlue() here.

2022-07-17 04:10 UTC, humdingerb commented on src/SidePanelView.cpp
> +		.AddGrid(B_USE_DEFAULT_SPACING, B_USE_DEFAULT_SPACING)
If the BTextControl gets a proper label, there's no need for an grid layout.
Also, it's easier to read, if the elements belonging to a layout group are indented in the code.

2022-07-17 04:10 UTC, humdingerb commented on src/SidePanelView.cpp
>  		.AddGlue(10)
No need for that AddGlue().

2022-07-17 04:10 UTC, humdingerb commented on src/SidePanelView.cpp
> +			fTextFilter->SetText(NULL);
Check the BTextControl description in BeBook/HaikuBook with what parameter SetText() is called.

2022-07-18 09:16 UTC, harshit-sharma-gits commented on src/SidePanelView.cpp
> +			fTextFilter->SetText(NULL);
I've checked the description, to clear out the contents, the parameter should be an empty string, that is, `""` 
Making the call as : `fTextFilter->SetText("");`. This clears the content of the BTextControl.
But it didn't happen when the Clear Button is pressed. There must be something issue with the messaging, can you help me figure out what is wrong here?

2022-07-18 10:53 UTC, humdingerb commented on src/SidePanelView.cpp
> +			fTextFilter->SetText(NULL);
I'm utterly baffled.
The message kFilterCleared never reaches MessageReceived()  - I put a printf() in the kFilterCleared-case,never shows up.
Totally weird. If I change the fFilterClearButton to send kMonthUpMessage, I can change the month with the Clear button. And vice-versa: using kFilterCleared as message for the fMonthUpButton, I can clear the filter text box...  Whaaaat?

Over to @nielx...

2022-07-19 06:00 UTC, nielx commented on src/SidePanelView.cpp
> +			fTextFilter->SetText(NULL);
Somewhere in the inheritance hierarchy of the BButton, there are a BControl, which inherits BInvoker. The BInvoker is the common helper that sends messages whenever an event relevant to the control happened (like checking a check box or clicking a button). The invoker needs a target.  This can be explicitly set. The BControl code sets the target to the window, if there is no custom target defined. The clear and apply messages are sent to the window and not the view. If you actually check the MessageReceived() in src/MainWindow.cpp, you can see that the other events are also received there, and are forwarded explicitly. This must be done for the event(s) you want to monitor on these new controls as well.

2022-07-19 11:49 UTC, humdingerb commented on src/SidePanelView.cpp
> +			fTextFilter->SetText(NULL);
Still weird. Why does the fMonthUpButton, created a few lines above, work as expected? Doing a `fFilterClearButton->SetTarget(this)` doesn't fix it either.

2022-07-20 12:01 UTC, harshit-sharma-gits commented
Hello!
I just tested out a function for filtering the events, `searchForKeywords()`. 

The idea is to to get the details of a particular event, including `Name`, `Place` & `Description`, in a string.
(So that the keywords can be searched in all of the three)

Then the keywords are searched in the event details. If any one of the keyword is found in the event details (irrespective of the case), then that event will be shown.

The filtering is working fine, but currently, to-be-searched keywords are not fetched by the Filter TextControl (need help regarding that), but hardcoded as `char* toSearch`

Also, I thought having the filtering done in `QueryDBManager` would be a great fit, because the events are directly loaded from File there.
Any suggestions on this?

2022-07-20 20:44 UTC, nielx commented on src/SidePanelView.cpp
> +			fTextFilter->SetText(NULL);
That works because of this line: https://github.com/HaikuArchives/Calendar/blob/4d200fc9a7b6605b9da0de41e88115ddbd67d143/src/MainWindow.cpp#L142

Setting the target does not work, because at the time the view is created, it is not yet attached to a window. The target is a looper plus an optional handler. There is no looper known at this time yet.

2022-07-20 20:47 UTC, nielx commented
> I defer to @nielx here, but I wonder if it wouldn't be better to do the filtering in EventTabView::_PopulateList(). When the filter string changes, you just have to trigger a _PopulateList(), while in QueryDBManager, you'll have to trigger a BQuery (which in turn tiggers a _PopulateList()).

I do not have a strong opinion on either approach. A fundamentalist view is that we use the database to perform querying, and thus these filters should be applied to the database query (database = filesystem in this case). A pragmatic view is that can do it locally, we do not need to load new data, we just do work on the current data. From a user perspective, I also wonder if it makes sense to show some additional stats that make clear how many items are filtered, much like in Excel you have this little bit in the status bar showing how many records of which total are visible when you use filters. But that would be for future iterations.

2022-07-20 20:48 UTC, nielx commented
@harshit-sharma-gits : if you make changes based on our comments, could you click on the Resolve button in this thread to mark which one you have completed?

2022-07-20 21:02 UTC, nielx commented
> Hello! I just tested out a function for filtering the events, `searchForKeywords()`.
> 
> The idea is to to get the details of a particular event, including `Name`, `Place` & `Description`, in a string. (So that the keywords can be searched in all of the three)

The overall approach looks sound, though I will do a more thorough review if you go for this one.

However, if you decide to implement this at the QueryDB level (see other comment), then I would argue that you should probably use the file systems query features to do this search. See the query.Push*() calls above on where it should factor in. A good pointer on what the query system can do can be found in the [user documentation](https://www.haiku-os.org/docs/userguide/en/queries.html).

Let us know what you decide and then we can review this part of the code.

2022-07-21 09:21 UTC, harshit-sharma-gits commented on src/SidePanelView.cpp
> +	fFilterApplyButton =
Sure, removed with the last commit

2022-07-21 09:22 UTC, harshit-sharma-gits commented on src/SidePanelView.cpp
> +		.AddStrut(80)
Added!

2022-07-21 09:23 UTC, harshit-sharma-gits commented on src/SidePanelView.cpp
>  		.AddGlue(10)
sure

2022-07-24 11:05 UTC, harshit-sharma-gits commented
Hello! I've moved the filter function to EventTabView's `_PopulateList()` function. 
The reason being :
If we add the filter at `QueryDBManager` level, then we would need to access the files every time, whenever the Filter Keywords are changed. And that would not be much efficient.
Instead, I think filtering out an existing list fetched from the `QueryDBManager` would be efficient.
The aim is to get the keywords from the TextControl and pass it to `_PopulateList()` where the filtering will take place.

But, I'm still stuck at sending the `kFilterCleared` Message.
Need suggestions.

2022-07-24 14:19 UTC, humdingerb commented
> But, I'm still stuck at sending the `kFilterCleared` Message.
> Need suggestions.

You shouldn't have let the clear-button-issue distract you too much. It's a side show, more important would be to get the contents of the fiter BTextView to where it's needed. However, there's the "AttachedToWindow()" hook function of BView where a SetTarget() might work to fix the apply button messaging.

2022-07-26 05:04 UTC, nielx commented on src/SidePanelView.cpp
> +		new BTextControl("FilterString", "Filter: ", NULL, new BMessage(kFilterCleared));
You should probably use a unique message constant instead of reusing kFilterCleared. 
This message will be sent to the MainWindow, like the others. From there you can forward it to the EventTabView and make that aware of the filter messages, so that it can be applied to the list.

2022-07-26 13:06 UTC, harshit-sharma-gits commented on src/SidePanelView.cpp
> +		new BTextControl("FilterString", "Filter: ", NULL, new BMessage(kFilterCleared));
Yeah, that was just for checking out the Clear Button, I have updated it now

2022-07-26 13:08 UTC, harshit-sharma-gits commented
Hello! I've added the hooks from `SidePanelView` and `EventTabView` to the `MainWindow`
and, now the Filtering seems to be working nicely; You may also see it [here](https://drive.google.com/file/d/1DIrfn43473RxbImjlKKm0K4hkmvPBYTp/view?usp=sharing)

2022-07-28 12:58 UTC, harshit-sharma-gits commented
> You shouldn't have let the clear-button-issue distract you too much. It's a side show, more important would be to get the contents of the fiter BTextView to where it's needed. However, there's the "AttachedToWindow()" hook function of BView where a SetTarget() might work to fix the apply button messaging.

I have tried this, still no improvement.
But, a rather off-chart approach worked!

Made a `EmptyFilterText()` public function in `SidePanelView`. Which, as the name suggests, clears the `TextControl`. And called this function from the `MainWindow` when the `kFilterCleared` case happens, like this :

```
case kFilterCleared:
    fSidePanelView->EmptyFilterText();
    break;
```

And voila, It works like a charm!

2022-07-28 19:25 UTC, nielx requested changes
Hi Harshit, thank you for the updates. It seems like you are well underway, but there is plenty to clean up before we can merge this. Could you make a start with the comments you find here? Let me know if there are any unclarities.

2022-07-28 19:25 UTC, nielx commented on src/EventTabView.h
> +	char*			filterKeywords;
Private variables start with an f prefix (see the other ones).
Also... you are using a C-style char* string that is allocated above with `strdup()`, but is never freed. At least you need to put a free in the destructor of the class, but even better would be to use a C++ object that does RAII and cleans up itself. In this case a BString or std::string would be better.

2022-07-28 19:25 UTC, nielx commented on src/EventTabView.cpp
> +			std::string(eventCategory);
This code block could be simplified by calling the `event->GetName()` etc. in the std::string constructor. You do not need the intermediate variables.

2022-07-28 19:25 UTC, nielx commented on src/EventTabView.cpp
> +			|| !_SearchForKeywords(wholeEvent.c_str()))
This code fragment right now is a bit inefficient. The reason is that you are creating the wholeEvent string every time this method is called, even if there is no filter text. It would be better to refactor the _SearchForKeywords method to take the event as parameter, and construct the wholeEvent string there if there is something to filter.

2022-07-28 19:25 UTC, nielx commented on src/EventTabView.cpp
> +	std::string s2 = filterKeywords;
Both these operation create unnecessary copies of data you already have. Please look at the other comments in this file on how this can be made more efficient, with less copying.

2022-07-28 19:25 UTC, nielx commented on src/EventTabView.cpp
> +	std::istringstream iss(s2);
I am not crazy about this approach, as it creates more copies of the data you already have. There are ways to rewrite this where you take an iterator to the start and end of every word in the string, and then run the find using the iterator.

2022-07-28 19:25 UTC, nielx commented on src/SidePanelView.cpp
> +	//fTextFilter->SetModificationMessage(new BMessage(kMonthUpMessage));
Please remember to cleanup commented out code before you submit your final PR

2022-07-28 19:25 UTC, nielx commented on src/SidePanelView.cpp
> +			fTextFilter->SetText("");
I don't get why you are clearing the filter here after receiving the message that the filter has changed.

2022-07-28 19:25 UTC, nielx commented on src/SidePanelView.cpp
> +	if (c && !c[0])						// Empty String
Do you need to do this check? you could also move the check for an empty string to your SearchForKeywords method.

2022-07-28 19:25 UTC, nielx commented on src/db/QueryDBManager.cpp
> +#include <algorithm>
I guess all changes in this file are no longer necessary?

2022-07-28 19:25 UTC, nielx commented on src/MainWindow.cpp
> +		case kFilterChanged:
Did you find out in the documentation if the kFilterChanged message itself actually contains the new string? In that case, you could simplify this code by just taking the string from the kFilterChanged message.

2022-07-30 06:57 UTC, harshit-sharma-gits commented on src/MainWindow.cpp
> +		case kFilterChanged:
I checked the BeBook. There are `AddString()` and `FindString()` functions. What we can do is attach the string to the message and then send it to the `MainWindow`, where we can retrieve the string and use it
But this is not possible due to the fact that we can't use `kFilterChanged` in SidePanelView. Also, this approach doesn't seem to be much efficient than the one, we're already at.

2022-07-30 06:57 UTC, harshit-sharma-gits commented on src/db/QueryDBManager.cpp
> +#include <algorithm>
Yes, I am reverting all the changes in `QueryDBManager.cpp`

2022-07-30 06:59 UTC, harshit-sharma-gits commented on src/SidePanelView.cpp
> +			fTextFilter->SetText("");
I think these lines are no longer necessary, as we are now dealing with theses two things in the MainWindow itself

2022-07-30 06:59 UTC, harshit-sharma-gits commented on src/SidePanelView.cpp
> +	//fTextFilter->SetModificationMessage(new BMessage(kMonthUpMessage));
Sure

2022-07-30 07:00 UTC, harshit-sharma-gits commented on src/EventTabView.cpp
> +			std::string(eventCategory);
Okay!

2022-07-30 11:40 UTC, harshit-sharma-gits commented on src/EventTabView.h
> +	char*			filterKeywords;
Sure, now I have used std::string for this. And the naming is corrected as well

2022-07-30 11:43 UTC, harshit-sharma-gits commented on src/EventTabView.cpp
> +			|| !_SearchForKeywords(wholeEvent.c_str()))
I have now modified the `_SearchForKeywords()` function to take the `event` as the parameter, and construct the `wholeEvent` string, when there is something to filter

2022-07-30 11:43 UTC, harshit-sharma-gits commented on src/EventTabView.cpp
> +	std::string s2 = filterKeywords;
Yes, now fixed

2022-07-30 11:48 UTC, harshit-sharma-gits commented on src/EventTabView.cpp
> +	std::istringstream iss(s2);
Please review the current approach

```
std::size_t start=0, end=0;
while((end = fFilterKeywords.find(' ', start)) != std::string::npos)
{
	if (wholeEvent.find(fFilterKeywords.substr(start, end - start))
		!= std::string::npos && end != start)
		return true;
	start = end + 1;
}

if(wholeEvent.find(fFilterKeywords.substr(start)) != std::string::npos
	&& end != start)
	return true;
```

It does not create the copy of the data, as was the case with previous one (using `std::istringstream iss(s2);`)

2022-07-30 11:49 UTC, harshit-sharma-gits commented on src/SidePanelView.cpp
> +	if (c && !c[0])						// Empty String
Yes, thanks for the suggestion! I have moved the empty string check to the `_SearchForKeywords()` method.

2022-07-30 11:51 UTC, harshit-sharma-gits commented on src/SidePanelView.cpp
> +			fTextFilter->SetText(NULL);
Regarding this issue;

The clear button seems to be working fine when triggered from the MainWindow itself.
But as always, I am open for further suggestions.

2022-07-31 07:04 UTC, nielx commented on src/EventTabView.cpp
> +	std::istringstream iss(s2);
I prefer this approach to the previous one, but substr() still creates a new string which copies the data. I will put some more comments in the code.

2022-07-31 07:13 UTC, nielx requested changes
It looks like you are almost there, but I am not quite sure whether your use of substr is working, and also you need to keep localization into account, so you must change that. I think there are other more efficient ways to do the searching, but if your current approach works and is performant enough (which it likely will be), then it is good enough for now.

2022-07-31 07:13 UTC, nielx commented on src/EventTabView.cpp
> +	if(wholeEvent.find(fFilterKeywords.substr(start)) != std::string::npos
Did you test this? [std::string::substr()](https://en.cppreference.com/w/cpp/string/basic_string/substr) takes two arguments, a start and the number of bytes you want to copy into the new string. Your current use seems to get it until the end, which will work if you are only searching for one keyword but is likely to break for more.

2022-07-31 07:13 UTC, nielx commented on src/EventTabView.h
> +	std::string		fFilterKeywords;
Do you think there is a way to get rid of this fFilterKeywords? I would argue that you can probably rewrite _SearchForKeywords() in such a way that it can take the keywords as a parameter, and that means you no longer need to store the keywords as a class variable.

2022-07-31 07:31 UTC, harshit-sharma-gits commented on src/EventTabView.cpp
> +	if(wholeEvent.find(fFilterKeywords.substr(start)) != std::string::npos
Yes, I have tested this, and it works really nicely.
Thing is that, inside the loop, it is able to read only upto the last keyword. So I have to put this check outside of the loop, to read the last keyword.

Let me explain this;
Suppose we give the following string to filter: `desk bath work`. Now, the program is supposed to look all three of them as seperate keywords (As we talked about this in a Video Chat early in the project)

Inside the loop, it is only able to read upto the last seperator (which in the case is a blank space `' '`), So the last keyword still remains, that is why I have put a check outside of the loop.

2022-07-31 07:33 UTC, harshit-sharma-gits commented on src/SidePanelView.h
> +	void			EmptyFilterText();
Sure

2022-07-31 08:02 UTC, harshit-sharma-gits commented on src/EventTabView.h
> +	std::string		fFilterKeywords;
I have tried to get rid of the fFilterEvents, but doing that will lead to pass the keywords down to `_PopulateList()` from `SetFilterString()` as argument.

The problem with that is `_PopulateList()` is being called from several other members, namely, `LoadEvents()` and `ToggleMode()`. This will lead to pass the keywords down to many members, which obviously is not needed.

2022-07-31 08:24 UTC, nielx commented on src/EventTabView.h
> +	std::string		fFilterKeywords;
Right! You are right that you need to store the keywords permanently then.

2022-07-31 08:52 UTC, harshit-sharma-gits commented on src/SidePanelView.cpp
> +		new BTextControl("FilterString", "Filter: ", NULL, new BMessage(kFilterChanged));
Both the `"Filter"` and `"Clear"` are now wrapped in B_TRANSLATE()

2022-08-01 06:02 UTC, nielx approved these changes
In my opinion the change is in good shape now, ready to merge.

2022-08-01 06:04 UTC, merged