Reminders
HaikuArchives/Calendar pull request #125
Opened 2022-08-31 17:26 UTC by harshit-sharma-gits

For Issue: #122

This PR is supposed to get the `QueryDBManager` code to be independent from the be_app, yet still working in the Calendar app.

Also, to remove the 'dead' functionality from the Calendar, such as:
GoogleCalendar/
utils/ICal

Both of these do not work as of now, but yes, they can serve as a starting point for implementing the same functionality.
What should we do with these?

@humdingerb suggested to have a note in the README about these not working.

2022-08-31 20:24 UTC, nielx requested changes
Please review the notes.

2022-08-31 20:24 UTC, nielx commented on main/src/App.cpp
> +		/*case kMenuSyncGCAL:
Normally you would not leave commented code in the codebase, but in this case there may be a good reason. You do need to add a comment here (and in other places) why you are leaving out this code.

2022-08-31 20:24 UTC, nielx commented on main/src/db/QueryDBManager.cpp
> +	BString defaultCat = "Default";
This needs to be reworked. You need to keep the current functionality of being able to provide a default category there. Have you thought about adding it as an argument to the constructor? Then in places where the QueryDBManager object is created, it can either be retrieved from the preferences (in the Calendar app), or be given a default value (in the daemon).

2022-09-01 13:17 UTC, harshit-sharma-gits commented on main/src/db/QueryDBManager.cpp
> +	BString defaultCat = "Default";
I think this can be done here:
* Make `fDefaulCat` as a class member
* Set it through a public function `QueryDBManager::SetDefaultCategory()` before wherever `GetAllCategories()` is being called

2022-09-01 13:17 UTC, harshit-sharma-gits commented on main/src/App.cpp
> +		/*case kMenuSyncGCAL:
I added note for the GCal Functionality

2022-09-01 20:13 UTC, nielx commented on main/src/db/QueryDBManager.cpp
> +	BString defaultCat = "Default";
I would actually make it a parameter to the constructor, and also have a SetDefaultCategory() method in case the preferences are updated.

2022-09-02 03:27 UTC, harshit-sharma-gits commented on main/src/db/QueryDBManager.cpp
> +	BString defaultCat = "Default";
I think that would create unnecessary clutter in the code. We'd have to provide `((App*) be_app)->GetPreferences()->fDefaultCategory` as an arguement wherever fDBManager is being declared (which is present in almost every class) yet we'd still have to update for the `fDefaultCat`.

2022-09-02 06:10 UTC, nielx reviewed
I think we are almost there. The only thing missing is that we make sure that the default category gets updated in all the places that have a QueryDBManager, when it is changed in the preferences.

2022-09-02 06:10 UTC, nielx commented on main/src/db/QueryDBManager.h
> +	void		SetDefaultCategory(BString cat);
Small improvement: please use the parameter name 'category'.

2022-09-02 06:10 UTC, nielx commented on main/src/db/QueryDBManager.h
> +	BString		fDefaultCat;
fDefaultCategory

2022-09-02 06:13 UTC, nielx commented on main/src/db/QueryDBManager.cpp
> +	BString defaultCat = "Default";
From a design standpoint that would be preferred though. If we think of every class as being designed as if it is meant to be part of a well-designed public API. In that case, a caller would not realize how often the default category is used. So you must either make this explicit through (a) adding the parameter to every method that will need a default category or (b) having it clearly be a class property, which is very explicit when it is a constructor parameter.

2022-09-02 10:14 UTC, harshit-sharma-gits commented on main/src/db/QueryDBManager.h
> +	BString		fDefaultCat;
Done

2022-09-02 10:14 UTC, harshit-sharma-gits commented on main/src/db/QueryDBManager.h
> +	void		SetDefaultCategory(BString cat);
Done

2022-09-02 10:16 UTC, harshit-sharma-gits commented on main/src/db/QueryDBManager.cpp
> +	BString defaultCat = "Default";
Okay, now the `fDefaultCategory` can be passed in the constructor.

I have tested it, the default category is being updated everywhere, when it is changed in the Preferences.

2022-09-03 03:36 UTC, harshit-sharma-gits commented
> I think we are almost there. The only thing missing is that we make sure that the default category gets updated in all the places that have a QueryDBManager, when it is changed in the preferences.

Should we use messages to send out a message to every class that needs to get the `defaultCategory` updated?
Well, the default category is being used in the Event Window to sort out the categories and it is updated in the Preferences.
There it is being update d

2022-09-03 06:05 UTC, nielx commented
I have re-reviewed the change, and I think you are right about the impact it is having on the readability and the scope of the changes. 
I have then reviewed the code to find how and where GetAllCategories() is used, and there are a few distinct places where the default category actually matters, namely in the PreferenceWindow.cpp (line 141), EventWindow.cpp (line 455 and 637) and CategoryWindow.cpp (line 138). 
With this insight, would it be better to drop the member data fDefaultCategory and make it an optional parameter to QueryDbManager::GetAllCategories() instead? In that case, you don't have to worry about updating the default category everywhere when the preferences are changed, and you can instead rely on existing functionality.

2022-09-03 09:21 UTC, harshit-sharma-gits commented
> With this insight, would it be better to drop the member data fDefaultCategory and make it an optional parameter to QueryDbManager::GetAllCategories() instead? In that case, you don't have to worry about updating the default category everywhere when the preferences are changed, and you can instead rely on existing functionality

`QueryDBManager::GetAllCategories()` is being called within `QueryDBManager.cpp` some times (in `QueryDBManager::AddCategory()` and `QueryDBManager::_Initialize()`). Thus, we cannot give the defaultCategory as an arguement there. How can we handle this?

2022-09-04 14:11 UTC, nielx commented
> > With this insight, would it be better to drop the member data fDefaultCategory and make it an optional parameter to QueryDbManager::GetAllCategories() instead? In that case, you don't have to worry about updating the default category everywhere when the preferences are changed, and you can instead rely on existing functionality
> 
> `QueryDBManager::GetAllCategories()` is being called within `QueryDBManager.cpp` some times (in `QueryDBManager::AddCategory()` and `QueryDBManager::_Initialize()`). Thus, we cannot give the defaultCategory as an arguement there. How can we handle this?

Please double check that the default category is not relevant for this particular use of the method. If not, then you can put the default argument of "" (empty string) in the class declaration

2022-09-04 18:38 UTC, harshit-sharma-gits commented
> Please double check that the default category is not relevant for this particular use of the method. If not, then you can put the default argument of "" (empty string) in the class declaration

Done!

2022-09-04 18:45 UTC, nielx reviewed
Almost there...

2022-09-04 18:45 UTC, nielx commented on main/src/db/QueryDBManager.h
> +	CategoryList* GetAllCategories(BString defaultCategory);
If you change this line to 
`CategoryList* GetAllCategories(BString defaultCategory = "")`
you don't need to have the empty strings where you don't have a specific default category.

2022-09-04 18:45 UTC, nielx commented on main/src/CategoryWindow.cpp
> +#include "Preferences.h"
You include preferences here...

2022-09-04 18:45 UTC, nielx commented on main/src/CategoryWindow.cpp
> +	fCategoryList = fDBManager->GetAllCategories("");
But then you do not use it to get the default category. And you want that, because below you are building a listview out of them and you want to keep the default on top

2022-09-04 18:56 UTC, harshit-sharma-gits commented on main/src/db/QueryDBManager.h
> +	CategoryList* GetAllCategories(BString defaultCategory);
Done!

2022-09-04 18:56 UTC, harshit-sharma-gits commented on main/src/CategoryWindow.cpp
> +	fCategoryList = fDBManager->GetAllCategories("");
Sure, corrected now

2022-09-04 18:58 UTC, nielx commented on main/src/db/QueryDBManager.h
> +				QueryDBManager(BString defaultCategory);
(outdated)

2022-09-04 18:59 UTC, harshit-sharma-gits commented on main/src/PreferenceWindow.cpp
> +	fDBManager = new QueryDBManager(((App*) be_app)->GetPreferences()->fDefaultCategory);
You've commented on a previous commit :)

Now the Default Category is not needed as the arguement in `QueryDBManager()`

I also have removed it from the class member. Now it is only being passed as an arguement to `QueryDBManager::GetAllCategories(BString defaultCategory = "")`

2022-09-04 21:09 UTC, nielx requested changes
Final points

2022-09-04 21:09 UTC, nielx commented on main/src/db/QueryDBManager.cpp
> +	if (GetAllCategories("")->CountItems() == 0) {
Since "" is now the default argument, you can change back this line.

2022-09-04 21:09 UTC, nielx commented on main/src/db/QueryDBManager.cpp
> +	CategoryList* categories = GetAllCategories("");
Ditto

2022-09-04 21:09 UTC, nielx commented on main/src/db/QueryDBManager.cpp
> +QueryDBManager::GetAllCategories(BString defaultCategory = "")
I am surprised this even compiles.
Default argument are in the declaration of a function/method (i.e. in the header) and should not repeated in the implementation.

2022-09-05 02:32 UTC, harshit-sharma-gits commented on main/src/db/QueryDBManager.cpp
> +QueryDBManager::GetAllCategories(BString defaultCategory = "")
Noted

2022-09-05 02:32 UTC, harshit-sharma-gits commented on main/src/db/QueryDBManager.cpp
> +	if (GetAllCategories("")->CountItems() == 0) {
Resolved

2022-09-05 02:32 UTC, harshit-sharma-gits commented on main/src/db/QueryDBManager.cpp
> +	CategoryList* categories = GetAllCategories("");
Resolved

2022-09-05 05:26 UTC, nielx approved these changes
Looking good. Tested changes, the default category is still at the top of the list in the Preferences, Categories and New Events windows.

2022-09-05 05:26 UTC, merged