Saving/Loading for events and GUI Changes for Calendar
HaikuArchives/Calendar pull request #127
Opened 2022-09-08 07:04 UTC by harshit-sharma-gits

For issue: #122 

The scope of this PR: Get the events to be saved with the Reminder as per the user's requirement

The GUI looks like this:

![EventManagerGUI Revised](https://user-images.githubusercontent.com/75475819/185587273-f3eaac88-59e8-42ac-b1b5-7f556d430a97.png)

2022-09-08 13:19 UTC, nielx requested changes
Some notes/comments. Could you explain in the commit message/PR description what the data model is going to be like? When is a reminder set? How to change/remove a reminder?

2022-09-08 16:14 UTC, harshit-sharma-gits commented on main/src/EventWindow.cpp
> +		reminderTime, time(NULL), status);
reminderTime is going to contain `-1` when the reminder is not set

2022-09-08 16:14 UTC, harshit-sharma-gits commented on main/src/EventWindow.cpp
> +		BMenuItem* mI = fReminderMenu->FindMarked();
Sure

2022-09-08 16:28 UTC, harshit-sharma-gits commented on main/src/EventWindow.cpp
> +	fCategoryList = fDBManager->GetAllCategories();
Yes, for sure. I removed that for testing the list, and it got left.. Reverting it asap

2022-09-08 16:35 UTC, harshit-sharma-gits commented on main/src/EventWindow.cpp
> +		else if (deltaTime%60 == 0) {	// minutes
Done

2022-09-08 16:47 UTC, harshit-sharma-gits commented on main/src/EventWindow.cpp
> +		time_t deltaTime = std::stoi(fTextReminderTime->Text());
The number isn't enforced anywhere. I think we should give this a tooltip, such as: `Enter an integer only` (?)

2022-09-08 17:06 UTC, harshit-sharma-gits commented
> Could you explain in the commit message/PR description what the data model is going to be like? When is a reminder set? 

While creating the event, the user can (if needed) set the reminder, let's say `x` hours/minutes/seconds before the event start time.
If the reminder is set by the user, it gets stored in the event file as `EVENT:REMINDER` attribute with the value `start time minus x`
And if, the reminder is not set by the user then no such attribute is added to the file.

> How to change/remove a reminder?

Simply click on the event inside the Calendar. It'll open the Event Window with the Event's details in it. The reminder is also modifiable there.

2022-09-08 18:09 UTC, nielx requested changes
Some more notes. I see two edge cases that need to be handled:

- Entering invalid characters in the reminder time.
- Updating the event time should update the reminder time.

2022-09-08 18:09 UTC, nielx commented on main/src/EventWindow.cpp
> +		time_t deltaTime = std::stoi(fTextReminderTime->Text());
It would be good to have a look how other apps do it. Maybe check some preferences?

If you are certain that the input only accepts numbers, you _may_ assume this call does not fail, otherwise you should try to catch any exceptions here to prevent the application from crashing.

2022-09-08 18:09 UTC, nielx commented on main/src/EventWindow.cpp
> +		reminderTime, time(NULL), status);
Right, I can see that now.

2022-09-08 20:17 UTC, humdingerb commented on main/src/EventWindow.cpp
> +		time_t deltaTime = std::stoi(fTextReminderTime->Text());
Check out TextView()'s DisallowChar();
For reference, I do something similar in Clipdinger's SettingsWindow.

2022-09-09 02:44 UTC, harshit-sharma-gits commented on main/src/EventWindow.cpp
> +		time_t deltaTime = std::stoi(fTextReminderTime->Text());
> If you are certain that the input only accepts numbers, you may assume this call does not fail, otherwise you should try to catch any exceptions here to prevent the application from crashing.

> Check out TextView()'s DisallowChar();
For reference, I do something similar in Clipdinger's SettingsWindow.

Thanks for the reference. Now only numbers are allowed in the `fTextReminderTime`

2022-09-09 02:46 UTC, harshit-sharma-gits commented
> Some more notes. I see two edge cases that need to be handled:
> * Entering invalid characters in the reminder time.

Now this is sorted by TextView()'s `DisallowChar()`

> * Updating the event time should update the reminder time.

This already is being handled. If the user changes the event's start time from the Calendar, the Reminder time changes as well.

2022-09-09 06:55 UTC, nielx commented
I did some testing and I found two issues. The first I want you to fix as part of this commit. The second you can create a ticket for to solve later.
1. When you create an entry with a reminder, and save it. And then you reopen the event and untick the reminder box, the reminder does not get deleted when you close the event. It will still be there when you reopen. Please fix.
2. If you put in a large number for the reminder, the data gets saved wrong. There should be some sort of validation/limits on how/when can be reminded. This can be deferred to later, though please create a follow up

2022-09-09 10:16 UTC, harshit-sharma-gits commented
> 1. When you create an entry with a reminder, and save it. And then you reopen the event and untick the reminder box, the reminder does not get deleted when you close the event. It will still be there when you reopen. Please fix.

This issue is now fixed.

> 2. If you put in a large number for the reminder, the data gets saved wrong. There should be some sort of validation/limits on how/when can be reminded. This can be deferred to later, though please create a follow up

I'll open an issue for this, and also mention this issue in the wrap-up blog post.

2022-09-09 11:37 UTC, nielx approved these changes

2022-09-09 11:38 UTC, merged