Querying the DB for next events
HaikuArchives/Calendar pull request #128
Opened 2022-09-09 19:49 UTC by harshit-sharma-gits

For issue: #122 

The scope of this PR: To get the events-to-be-reminded in `fEventList` and manage it by adding/removing the events as per the requirement.

2022-09-09 19:56 UTC, harshit-sharma-gits commented
This commit is not complete yet. Currently, it only fetches the list from `QueryDBManager` and add events to the list when an event is added.

I am working on the attribute change and event removing.

2022-09-09 23:14 UTC, nielx requested changes
There's a lot to unpack. I did a first glance, but as you write, you still have to finish the work.

I do want to make clear that I will not approve a design where every individual node is going to be watched. This is not scalable. Even if it works for a little test data, you are going to run into limits if someone seriously uses the application.

I also don't really understand how this is supposed to work. There is an fEventList. You manually add things there, but you initialize it using a function in the QueryDBManager... Can you explain how it is supposed to work? What triggers changes? How will you determine what events to notify for next?

2022-09-09 23:14 UTC, nielx commented on daemon/src/CalendarDaemon.h
> +	QueryDBManager*		fDBManager;
Why do you use a pointer here, instead of a value member?

2022-09-09 23:14 UTC, nielx commented on daemon/src/CalendarDaemon.cpp
> +	fEventList()
No need to initialize if you initialize it later on in your constructor.

2022-09-10 04:28 UTC, harshit-sharma-gits commented on daemon/src/CalendarDaemon.cpp
> +	fEventList()
Okay

2022-09-10 04:30 UTC, harshit-sharma-gits commented on daemon/src/CalendarDaemon.h
> +	QueryDBManager*		fDBManager;
There's no specific reason, we can use the fDBManager as a value member instead.

2022-09-10 04:43 UTC, harshit-sharma-gits commented
> I do want to make clear that I will not approve a design where every individual node is going to be watched. This is not scalable. Even if it works for a little test data, you are going to run into limits if someone seriously uses the application.

Yes, we can leave this (the attribute part) for now with a note to work on this post GSoC (as I stated in the mail)

> I also don't really understand how this is supposed to work. There is an fEventList. You manually add things there, but you initialize it using a function in the QueryDBManager... Can you explain how it is supposed to work? What triggers changes? How will you determine what events to notify for next?

`QueryDBManager::GetEventsToNotify()` fetches a list of event that are to be reminded, so I am using this to get the events list instead of making a function for it myself (code re-use).
The changes are triggered by Node Monitor, which we are using on the events directory. That is, if any entry is created/removed from the events directory, it triggers the daemon to "refresh" the events list.

The idea is to get the events list when the daemon is started and then node monitor the events directory to get the updates (adding/removing) which we can manually add/remove to/from the `fEventList`.
What we can alternately do is, in any case (event adding/removing) we can fetch for a fresh list of the events with the `fDBManager->GetEventsToNotify()` and update the `fEventList`. Would that be better option?

2022-09-10 16:00 UTC, nielx commented on main/src/db/QueryDBManager.h
> +	Event*		FileToEvent(entry_ref* ref);
With your latest approach, do you still need to be making this public?

2022-09-10 16:02 UTC, harshit-sharma-gits commented on main/src/db/QueryDBManager.h
> +	Event*		FileToEvent(entry_ref* ref);
`FileToEvent()` won't be required to be public now, I should revert this to private.

2022-09-10 19:26 UTC, nielx commented
For issue: https://github.com/HaikuArchives/Calendar/issues/122

The scope of this PR: To get the events-to-be-reminded in fEventList and manage it by adding/removing the events as per the requirement.

2022-09-10 19:26 UTC, merged